### ISSUE TITLE
Enable standard query parameter `?q=<term>`

### ISSUE THREAD

**Issue by coolaj86** [nalgeon/sqlpkg#3]
Enabling `?q=<term>` is part of what allows browser omnibars to recognize and use your registry as a valid "search engine".

As in the behavior where can type `sqlpkg.org <space> <tab> <search-term>` and hit enter to get a result.

This is specific to Chrome, but I believe it works similarly for all major browsers: <https://www.groovypost.com/howto/howto/use-google-site-search-from-chrome-omni-bar/>

There's probably also some metatag or some such.

**Comment by mikeschinkel** [comment]
I'll second this because I wanted to use in the `sqlpkg` badge for [this PR](https://github.com/asg017/sqlite-regex/issues/16):


![CleanShot 2024-01-30 at 06 41 11@2x](https://github.com/nalgeon/sqlpkg/assets/153285/24eda84d-6c8b-4ca8-96de-e6d41cd1ef96)

**Comment by nalgeon** [comment]
Not sure what the connection is and how it would help.

**Comment by mikeschinkel** [comment]
@nalgeon — The connection is that there is no current way to link this badge to a page on your [sqlpkg.org](https://sqlpkg.org) that is specific to a given Sqlite extension that other package sites have:

[![sqlpkg CLI](https://img.shields.io/badge/dynamic/json?url=https%3A%2F%2Fapi.github.com%2Frepos%2Fasg017%2Fsqlite-regex%2Freleases%2Flatest&query=name&logo=sqlite&label=sqlpkg%20CLI&color=%2385cff3)](https://sqlpkg.org/)

Note the above badge may say "invalid" which I suspect could be because Github comments (preview) are somehow disabling it, but that badge is definitely displaying the version number [**here**](https://github.com/mikeschinkel/sqlite-regex/tree/main?tab=readme-ov-file#installing) even if its link doesn't take you to info about the specific extension when you click it.

-------
BTW, I jumped on this issue rather than create a new issue because using a search query could easily meet the use-case:

```
https://sqlpkg.org/?q=asg017/regex
```

However, what I really am asking for is addition of an extension-specific page template at a displayed at an extension-specific, if that is possible given how you are hosting, e.g:

```
https://sqlpkg.org/extensions/asg017/regex
```

**Comment by nalgeon** [comment]
I've added support for `?q=<term>` in the URL (e.g., https://sqlpkg.org/?q=asg017/regex). No current plans to add other features mentioned above.

**Comment by mikeschinkel** [comment]
@nalgeon — You are awesome! 😎 

Thank you.
